<a href="https://colab.research.google.com/github/kalebsampaco/DataEngineering_Platzi_Course/blob/master/Copia_de_Curso_de_Manipulaci%C3%B3n_y_an%C3%A1lisis_de_datos_con_Pandas_y_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
lista = [1,2,3,4,5]

In [ ]:
lista[0]

1

In [ ]:
lista[2]

3

In [ ]:
lista[-1]

5

In [ ]:
lista + [10]

[1, 2, 3, 4, 5, 10]

In [ ]:
import numpy as np


In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
np.array([1,2,3,4,5]) + 10

array([11, 12, 13, 14, 15])

In [ ]:
np.array([1,2,3,4,5]).shape

(5,)

In [ ]:
matriz = np.array([[1,2,3,4],[6,7,8,9]])
matriz

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [ ]:
matriz.shape

(2, 4)

In [ ]:
matriz[0]

array([1, 2, 3, 4])

In [ ]:
matriz[1]

array([6, 7, 8, 9])

In [ ]:
matriz[0][0]


1

In [ ]:
matriz[0][1]

2

In [ ]:
matriz[1][0]

6

#Series e indexanción y selección de datos

In [ ]:
import pandas as pd

In [ ]:
pd.Series([10,9,8,7,6])

0    10
1     9
2     8
3     7
4     6
dtype: int64

In [ ]:
sr = pd.Series([10,9,8,7,6])

In [ ]:
sr.values

array([10,  9,  8,  7,  6])

In [ ]:
sr.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
sr.shape

(5,)

In [ ]:
sr[3]

7

In [ ]:
sr[[0,4,2]]

0    10
4     6
2     8
dtype: int64

In [ ]:
sr = pd.Series([10,9,8,7,6], index=['a','b','c','d','e'])
sr

a    10
b     9
c     8
d     7
e     6
dtype: int64

In [ ]:
sr['c']

8

In [ ]:
sr[['c','d','e']]

c    8
d    7
e    6
dtype: int64

In [ ]:
sr['b':'e']

b    9
c    8
d    7
e    6
dtype: int64

In [ ]:
{'CO':100,'MX':200,'AR':200}

{'AR': 200, 'CO': 100, 'MX': 200}

In [ ]:
dict_data = {'CO':100,'MX':200,'AR':200}
dict_data

{'AR': 200, 'CO': 100, 'MX': 200}

In [ ]:
dict_data.keys()

dict_keys(['CO', 'MX', 'AR'])

In [ ]:
dict_data['MX']

200

In [ ]:
pd.Series(dict_data)

CO    100
MX    200
AR    200
dtype: int64

In [ ]:
pd.Series(dict_data, index=['CO','MX','PE'])

CO    100.0
MX    200.0
PE      NaN
dtype: float64

In [ ]:
import numpy as np

In [ ]:
np.nan

nan

In [ ]:
np.nan + 10

nan

In [ ]:
sr = pd.Series(dict_data, index=['CO','MX','PE'])
sr

CO    100.0
MX    200.0
PE      NaN
dtype: float64

In [ ]:
sr.isnull()

CO    False
MX    False
PE     True
dtype: bool

In [ ]:
sr.notnull()

CO     True
MX     True
PE    False
dtype: bool

#De paneles de datos a DataFrame

In [ ]:
import pandas as pd
pd.__version__

'1.1.5'

In [ ]:
!pip install --upgrade pandas

Requirement already up-to-date: pandas in /usr/local/lib/python3.6/dist-packages (1.1.5)


In [ ]:
dict_data = {'CO':[100, 800, 200],'MX':[100, 200, 300],'AR':[300, 500, 400]}
dict_data

{'AR': [300, 500, 400], 'CO': [100, 800, 200], 'MX': [100, 200, 300]}

In [ ]:
df = pd.DataFrame(dict_data)
df

CO   MX   AR
0  100  100  300
1  800  200  500
2  200  300  400

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
dict_data = {
    'edad': [10,9,13,14,12,11,12],
    'cm': [115,110,130,155,125,120,125],
    'pais':['co','mx','co','mx','mx','ch','ch'],
    'genero':['M','F','F','M','M','M','F'],
    'Q1':[5,10,8,np.nan,7,8,3],
    'Q2':[7,9,9,8,8,8,9]
}
dict_data

{'Q1': [5, 10, 8, nan, 7, 8, 3],
 'Q2': [7, 9, 9, 8, 8, 8, 9],
 'cm': [115, 110, 130, 155, 125, 120, 125],
 'edad': [10, 9, 13, 14, 12, 11, 12],
 'genero': ['M', 'F', 'F', 'M', 'M', 'M', 'F'],
 'pais': ['co', 'mx', 'co', 'mx', 'mx', 'ch', 'ch']}

In [ ]:
df = pd.DataFrame(dict_data)
df

edad   cm pais genero    Q1  Q2
0    10  115   co      M   5.0   7
1     9  110   mx      F  10.0   9
2    13  130   co      F   8.0   9
3    14  155   mx      M   NaN   8
4    12  125   mx      M   7.0   8
5    11  120   ch      M   8.0   8
6    12  125   ch      F   3.0   9

In [ ]:
df = pd.DataFrame(dict_data, index=['ana','benito','camilo','daniel','erika','fabian','gabriela'])
df

edad   cm pais genero    Q1  Q2
ana         10  115   co      M   5.0   7
benito       9  110   mx      F  10.0   9
camilo      13  130   co      F   8.0   9
daniel      14  155   mx      M   NaN   8
erika       12  125   mx      M   7.0   8
fabian      11  120   ch      M   8.0   8
gabriela    12  125   ch      F   3.0   9

In [ ]:
df.index

Index(['ana', 'benito', 'camilo', 'daniel', 'erika', 'fabian', 'gabriela'], dtype='object')

In [ ]:
df.columns

Index(['edad', 'cm', 'pais', 'genero', 'Q1', 'Q2'], dtype='object')

In [ ]:
df.values

array([[10, 115, 'co', 'M', 5.0, 7],
       [9, 110, 'mx', 'F', 10.0, 9],
       [13, 130, 'co', 'F', 8.0, 9],
       [14, 155, 'mx', 'M', nan, 8],
       [12, 125, 'mx', 'M', 7.0, 8],
       [11, 120, 'ch', 'M', 8.0, 8],
       [12, 125, 'ch', 'F', 3.0, 9]], dtype=object)

In [ ]:
df['edad']

ana         10
benito       9
camilo      13
daniel      14
erika       12
fabian      11
gabriela    12
Name: edad, dtype: int64

In [ ]:
df[['edad', 'cm', 'Q1']]

edad   cm    Q1
ana         10  115   5.0
benito       9  110  10.0
camilo      13  130   8.0
daniel      14  155   NaN
erika       12  125   7.0
fabian      11  120   8.0
gabriela    12  125   3.0

In [ ]:
df.loc['ana', ['edad', 'cm', 'Q1']]

edad     10
cm      115
Q1        5
Name: ana, dtype: object

In [ ]:
df.loc[['ana','erika'], ['edad', 'cm', 'Q1']]

edad   cm   Q1
ana      10  115  5.0
erika    12  125  7.0

In [ ]:
df.loc['daniel', 'Q1']

nan

In [ ]:
df


edad   cm pais genero    Q1  Q2
ana         10  115   co      M   5.0   7
benito       9  110   mx      F  10.0   9
camilo      13  130   co      F   8.0   9
daniel      14  155   mx      M   NaN   8
erika       12  125   mx      M   7.0   8
fabian      11  120   ch      M   8.0   8
gabriela    12  125   ch      F   3.0   9

In [ ]:
df.iloc[2,1]

130

In [ ]:
df.iloc[2,[1,3]]

cm        130
genero      F
Name: camilo, dtype: object

In [ ]:
df.iloc[[2,4,5],[1,3]]

cm genero
camilo  130      F
erika   125      M
fabian  120      M

In [ ]:
df.iloc[:,[1,3]]

cm genero
ana       115      M
benito    110      F
camilo    130      F
daniel    155      M
erika     125      M
fabian    120      M
gabriela  125      F

In [ ]:
df['edad'] >= 12

ana         False
benito      False
camilo       True
daniel       True
erika        True
fabian      False
gabriela     True
Name: edad, dtype: bool

In [ ]:
df[df['edad'] >= 12]

edad   cm pais genero   Q1  Q2
camilo      13  130   co      F  8.0   9
daniel      14  155   mx      M  NaN   8
erika       12  125   mx      M  7.0   8
gabriela    12  125   ch      F  3.0   9

In [ ]:
df[(df['edad'] >= 12) & (df['pais'] == 'mx')]

edad   cm pais genero   Q1  Q2
daniel    14  155   mx      M  NaN   8
erika     12  125   mx      M  7.0   8

In [ ]:
df.query('edad > 12')

edad   cm pais genero   Q1  Q2
camilo    13  130   co      F  8.0   9
daniel    14  155   mx      M  NaN   8

In [ ]:
df['Q2']>=df['Q1']

ana          True
benito      False
camilo       True
daniel      False
erika        True
fabian       True
gabriela     True
dtype: bool

In [ ]:
df[df['Q2']>=df['Q1']]

edad   cm pais genero   Q1  Q2
ana         10  115   co      M  5.0   7
camilo      13  130   co      F  8.0   9
erika       12  125   mx      M  7.0   8
fabian      11  120   ch      M  8.0   8
gabriela    12  125   ch      F  3.0   9

#Indexado y manejo de archivos CSV

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
% cd '/content/drive/MyDrive/Colab Notebooks'
!ls

/content/drive/MyDrive/Colab Notebooks
'Chapter 1 - Word Vectors - Inspect a Pretrained Model.ipynb'
'Chapter 2 - Skip-gram Architecture.ipynb'
 clasificador_imagenes_TF_Keras
'Copia de Chapter 2 - Skip-gram Architecture.ipynb'
 db1
'Escuela de data Science'
 imagenes
'Inteligencia artificial y machine learning'
 Jupyter
'Machine Learning con python'
 TensorFlow


In [ ]:
'Hola {}'.format('mundo')
'/gdrive/MyDrive/Colab Notebooks/db/test.csv'

'/gdrive/MyDrive/Colab Notebooks/db/test.csv'

In [ ]:
!mkdir /content/drive/MyDrive/Colab\ Notebooks/db

mkdir: cannot create directory ‘/content/drive/MyDrive/Colab Notebooks/db’: File exists


In [ ]:
dir_pandas = '/content/drive/MyDrive/Colab Notebooks/db/{}'.format('test.csv')
dir_pandas

'/content/drive/MyDrive/Colab Notebooks/db/test.csv'

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dict_data = {
    'edad': [10,9,13,14,12,11,12],
    'cm': [115,110,130,155,125,120,125],
    'pais':['co','mx','co','mx','mx','ch','ch'],
    'genero':['M','F','F','M','M','M','F'],
    'Q1':[5,10,8,np.nan,7,8,3],
    'Q2':[7,9,9,8,8,8,9]
}
dict_data

{'Q1': [5, 10, 8, nan, 7, 8, 3],
 'Q2': [7, 9, 9, 8, 8, 8, 9],
 'cm': [115, 110, 130, 155, 125, 120, 125],
 'edad': [10, 9, 13, 14, 12, 11, 12],
 'genero': ['M', 'F', 'F', 'M', 'M', 'M', 'F'],
 'pais': ['co', 'mx', 'co', 'mx', 'mx', 'ch', 'ch']}

In [ ]:
df = pd.DataFrame(dict_data)
df

edad   cm pais genero    Q1  Q2
0    10  115   co      M   5.0   7
1     9  110   mx      F  10.0   9
2    13  130   co      F   8.0   9
3    14  155   mx      M   NaN   8
4    12  125   mx      M   7.0   8
5    11  120   ch      M   8.0   8
6    12  125   ch      F   3.0   9

In [ ]:
dir_pandas = '/content/drive/MyDrive/Colab Notebooks/db/{}'.format('test.csv')
dir_pandas

'/content/drive/MyDrive/Colab Notebooks/db/test.csv'

In [ ]:
df.to_csv(dir_pandas, index = False)

In [ ]:
!ls /content/drive/MyDrive/Colab\ Notebooks/db

test.csv


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/db/test.csv')
df

edad   cm pais genero    Q1  Q2
0    10  115   co      M   5.0   7
1     9  110   mx      F  10.0   9
2    13  130   co      F   8.0   9
3    14  155   mx      M   NaN   8
4    12  125   mx      M   7.0   8
5    11  120   ch      M   8.0   8
6    12  125   ch      F   3.0   9

In [ ]:
df.to_csv(dir_pandas, sep= '|', index = False)

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/db/test.csv', sep='|')
df

edad   cm pais genero    Q1  Q2
0    10  115   co      M   5.0   7
1     9  110   mx      F  10.0   9
2    13  130   co      F   8.0   9
3    14  155   mx      M   NaN   8
4    12  125   mx      M   7.0   8
5    11  120   ch      M   8.0   8
6    12  125   ch      F   3.0   9

In [ ]:
dir_pandas = '/content/drive/MyDrive/Colab Notebooks/db/{}'
dir_pandas

'/content/drive/MyDrive/Colab Notebooks/db/{}'

In [ ]:
df.to_excel(dir_pandas.format('test.xlsx'), index=False, sheet_name='Hoja_uno')

In [ ]:
pd.read_excel(dir_pandas.format('test.xlsx'))

edad   cm pais genero    Q1  Q2
0    10  115   co      M   5.0   7
1     9  110   mx      F  10.0   9
2    13  130   co      F   8.0   9
3    14  155   mx      M   NaN   8
4    12  125   mx      M   7.0   8
5    11  120   ch      M   8.0   8
6    12  125   ch      F   3.0   9

In [ ]:
df.to_json(dir_pandas.format('test.json'))

In [ ]:
pd.read_json(dir_pandas.format('test.json'))

edad   cm pais genero    Q1  Q2
0    10  115   co      M   5.0   7
1     9  110   mx      F  10.0   9
2    13  130   co      F   8.0   9
3    14  155   mx      M   NaN   8
4    12  125   mx      M   7.0   8
5    11  120   ch      M   8.0   8
6    12  125   ch      F   3.0   9

In [ ]:
df.to_pickle(dir_pandas.format('test.pkl'))

In [ ]:
pd.read_pickle(dir_pandas.format('test.pkl'))

edad   cm pais genero    Q1  Q2
0    10  115   co      M   5.0   7
1     9  110   mx      F  10.0   9
2    13  130   co      F   8.0   9
3    14  155   mx      M   NaN   8
4    12  125   mx      M   7.0   8
5    11  120   ch      M   8.0   8
6    12  125   ch      F   3.0   9

In [ ]:
df.to_parquet(dir_pandas.format('test.parquet'))

In [ ]:
df.to_hdf(dir_pandas.format('test.hdf'),key='data',format='table')

In [ ]:
pd.read_parquet(dir_pandas.format('test.parquet'))

edad   cm pais genero    Q1  Q2
0    10  115   co      M   5.0   7
1     9  110   mx      F  10.0   9
2    13  130   co      F   8.0   9
3    14  155   mx      M   NaN   8
4    12  125   mx      M   7.0   8
5    11  120   ch      M   8.0   8
6    12  125   ch      F   3.0   9

In [ ]:
pd.read_hdf(dir_pandas.format('test.hdf'))

edad   cm pais genero    Q1  Q2
0    10  115   co      M   5.0   7
1     9  110   mx      F  10.0   9
2    13  130   co      F   8.0   9
3    14  155   mx      M   NaN   8
4    12  125   mx      M   7.0   8
5    11  120   ch      M   8.0   8
6    12  125   ch      F   3.0   9

#Conexión con tipos de bases de datos SQL

In [ ]:
!pip install psycopg2


You should consider upgrading via the 'c:\programdata\anaconda3\envs\tensorflow\python.exe -m pip install --upgrade pip' command.


In [ ]:
import pandas as pd
import psycopg2


In [ ]:
conn_sql = psycopg2.connect(user = "postgres",
                            password = "W1ll14m1234",
                            host = 'localhost',
                            port = "5432",
                            database = "postgres")

In [ ]:
query_sql = '''
select *
from platzi.alumnos
limit 10
'''

In [ ]:
df = pd.read_sql(query_sql, conn_sql)
df.head(5)

id  nombre    apellido                    email  colegiatura  \
0   1   Wanda  Billington  wbillington0@nsw.gov.au       5000.0   
1   2  Blayne     Wakeley      bwakeley1@google.cn       2500.0   
2   3   Hilde     Matiewe       hmatiewe2@hibu.com       2300.0   
3   4  Leanna        None       ldusey3@ebay.co.uk       2000.0   
4   5   Maire     Garnall  mgarnall4@artisteer.com       4800.0   

  fecha_incorporacion  carrera_id  tutor_id  
0 2020-05-17 22:49:29          23         9  
1 2018-09-01 17:51:49          40        26  
2 2020-07-18 00:03:21          48        25  
3 2018-02-05 17:28:38          36        14  
4 2020-08-04 03:43:57          14         7

####SQL Server

In [ ]:
!pip install pyodbc

     |████████████████████████████████| 276kB 5.9MB/s 
  ERROR: Failed building wheel for pyodbc
  Running setup.py clean for pyodbc
Failed to build pyodbc
    Running setup.py install for pyodbc ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a8awg56z/pyodbc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a8awg56z/pyodbc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-kzj_j0iz/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.


In [ ]:
import pandas as pd
import pyodbc

ModuleNotFoundError: ignored

In [ ]:
driver = '{SQL Server}'
server_name = 'server_name'
db_name = 'database_name'
user = 'user'
password = 'password'
sql_conn = pyodbc.connect('''
DRIVER={};SERVER={};DATABASE={};UID={};PWD={};
Trusted_Connection=yes
'''.format(driver, server_name, db_name, user, password))

NameError: ignored

In [ ]:
##Con DNS
dsn = 'odbc_datasource_name'
sql_conn = pyodbc.connect('''
DSN={};UID={};PWD={};Trusted_Connection=yes;
'''.format(dsn, user, password))
Seguido simplemente definimos nuestra query en SQL:	
query_sql = 'select * from table_name limit 10'

SyntaxError: ignored

In [ ]:
df = pd.read_sql(query_sql, sql_conn)
df.head(5)

NameError: ignored

###MySQL / Oracle / Otras:

In [ ]:
!pip install sqlalchemy

You should consider upgrading via the 'c:\programdata\anaconda3\envs\tensorflow\python.exe -m pip install --upgrade pip' command.


In [ ]:
import pandas as pd
import sqlalchemy as sql
##Escogemos nuestra base de datos, Oracle, MySql o la de tu preferencia:
database_mysql = 'mysql'
database_oracle = 'oracle'

In [ ]:
!pip install mysql-python

  ERROR: Command errored out with exit status 1:

  Running setup.py clean for mysql-python
Failed to build mysql-python
    Running setup.py install for mysql-python: started
    Running setup.py install for mysql-python: finished with status 'error'



   command: 'c:\programdata\anaconda3\envs\tensorflow\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\WILLIA~1\\AppData\\Local\\Temp\\pip-install-y95n_l7x\\mysql-python\\setup.py'"'"'; __file__='"'"'C:\\Users\\WILLIA~1\\AppData\\Local\\Temp\\pip-install-y95n_l7x\\mysql-python\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\WILLIA~1\AppData\Local\Temp\pip-wheel-1op_2l5g'
       cwd: C:\Users\WILLIA~1\AppData\Local\Temp\pip-install-y95n_l7x\mysql-python\
  Complete output (29 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  copying _mysql_exceptions.py -> build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\MySQLdb
  copying MySQLdb\__init__.py -> build\lib.win-amd64-3.6\MySQLdb
  copying MySQLdb\converters.py -> build\lib.win-

In [ ]:
!pip install mysqlclient


         cwd: C:\Users\WILLIA~1\AppData\Local\Temp\pip-install-y95n_l7x\mysql-python\
    Complete output (29 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    copying _mysql_exceptions.py -> build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\MySQLdb
    copying MySQLdb\__init__.py -> build\lib.win-amd64-3.6\MySQLdb
    copying MySQLdb\converters.py -> build\lib.win-amd64-3.6\MySQLdb
    copying MySQLdb\connections.py -> build\lib.win-amd64-3.6\MySQLdb
    copying MySQLdb\cursors.py -> build\lib.win-amd64-3.6\MySQLdb
    copying MySQLdb\release.py -> build\lib.win-amd64-3.6\MySQLdb
    copying MySQLdb\times.py -> build\lib.win-amd64-3.6\MySQLdb
    creating build\lib.win-amd64-3.6\MySQLdb\constants
    copying MySQLdb\constants\__init__.py -> build\lib.win-amd64-3.6\MySQLdb\constants
    copying MySQLdb\constants\CR.py -> build\lib.win-amd64-3.6\MySQLdb\constants
    copying MySQLdb\constants\FIELD_

You should consider upgrading via the 'c:\programdata\anaconda3\envs\tensorflow\python.exe -m pip install --upgrade pip' command.


In [ ]:
user = 'root'
password = 'W1ll14m1234'
host = 'localhost:3306'
database = 'platzi_operation'

conn_string = '{}://{}:{}@{}/{}'.format(
database_mysql, user, password, host, database)

sql_conn = sql.create_engine(conn_string)

In [ ]:
query_sql = '''
select *
from authors
limit 10
'''

In [ ]:
df = pd.read_sql(query_sql, sql_conn)
df.head(5)

author_id                name nationality
0          1          Sam Altman         USA
1          2         Freddy Vega         COL
2          3  Arthur Conan Doyle         GBR
3          4     Chuck Palahniuk         USA
4          5          Juan Rulfo         MEX

In [ ]:
##La libreria sqlalchemy también soporta PostgreSQL y otras fuentes de datos.